<?php

namespace Drupal\sir\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\rep\Constant;
use Drupal\rep\Utils;
use Drupal\rep\Entity\Tables;
use Drupal\rep\Vocabulary\VSTOI;

class AddDetectorStemForm extends FormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'add_detectorstem_form';
  }

  protected $sourceDetectorStemUri;

  protected $sourceDetectorStem;

  public function getSourceDetectorStemUri() {
    return $this->sourceDetectorStemUri;
  }

  public function setSourceDetectorStemUri($uri) {
    return $this->sourceDetectorStemUri = $uri; 
  }

  public function getSourceDetectorStem() {
    return $this->sourceDetectorStem;
  }

  public function setSourceDetectorStem($obj) {
    return $this->sourceDetectorStem = $obj; 
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $sourcedetectorstemuri = NULL) {

    // ESTABLISH API SERVICE
    $api = \Drupal::service('rep.api_connector');

    // HANDLE SOURCE DETECTOR STEM,  IF ANY
    $sourceuri=$sourcedetectorstemuri;
    if ($sourceuri === NULL || $sourceuri === 'EMPTY') {
      $this->setSourceDetectorStem(NULL);
      $this->setSourceDetectorStemUri('');
    } else {
      $sourceuri_decode=base64_decode($sourceuri);
      $this->setSourceDetectorStemUri($sourceuri_decode);
      $rawresponse = $api->getUri($this->getSourceDetectorStemUri());
      $obj = json_decode($rawresponse);
      if ($obj->isSuccessful) {
        $this->setSourceDetectorStem($obj->body);
      } else {
        $this->setSourceDetectorStem(NULL);
        $this->setSourceDetectorStemUri('');
      }
    }
    $disabledDerivationOption = ($this->getSourceDetectorStem() === NULL);

    $tables = new Tables;
    $languages = $tables->getLanguages();
    $derivations = $tables->getGenerationActivities();

    $sourceContent = '';
    if ($this->getSourceDetectorStem() != NULL) {
      $sourceContent = $this->getSourceDetectorStem()->hasContent;
    }

    $form['detectorstem_content'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Content'),
    ];
    $form['detectorstem_language'] = [
      '#type' => 'select',
      '#title' => $this->t('Language'),
      '#options' => $languages,
      '#default_value' => 'en',
    ];
    $form['detectorstem_version'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Version'),
    ];
    $form['detectorstem_description'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Description'),
    ];
    $form['detectorstem_was_derived_from'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Was Derived From'),
      '#default_value' => $sourceContent,
      '#disabled' => TRUE,
    ];
    $form['detectorstem_was_generated_by'] = [
      '#type' => 'select',
      '#title' => $this->t('Was Generated By'),
      '#options' => $derivations,
      '#default_value' => Constant::DEFAULT_WAS_GENERATED_BY,
      '#disabled' => $disabledDerivationOption,
    ];
    $form['save_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Save'),
      '#name' => 'save',
    ];
    $form['cancel_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Cancel'),
      '#name' => 'back',
    ];
    $form['bottom_space'] = [
      '#type' => 'item',
      '#title' => t('<br><br>'),
    ];

    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    $submitted_values = $form_state->cleanValues()->getValues();
    $triggering_element = $form_state->getTriggeringElement();
    $button_name = $triggering_element['#name'];

    if ($button_name != 'back') {
      if(strlen($form_state->getValue('detectorstem_content')) < 1) {
        $form_state->setErrorByName('detectorstem_content', $this->t('Please enter a valid content'));
      }
      if(strlen($form_state->getValue('detectorstem_language')) < 1) {
        $form_state->setErrorByName('detectorstem_language', $this->t('Please enter a valid language'));
      }
      if(strlen($form_state->getValue('detectorstem_version')) < 1) {
        $form_state->setErrorByName('detectorstem_version', $this->t('Please enter a valid version'));
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $submitted_values = $form_state->cleanValues()->getValues();
    $triggering_element = $form_state->getTriggeringElement();
    $button_name = $triggering_element['#name'];

    if ($button_name === 'back') {
      $form_state->setRedirectUrl(Utils::selectBackUrl('detectorstem'));
      return;
    } 

    try {

      $wasDerivedFrom = '';
      if ($this->getSourceDetectorStemUri() === NULL) {
        $wasDerivedFrom = 'null';
      } else {
        $wasDerivedFrom = $this->getSourceDetectorStemUri();
      }
      $wasGeneratedBy = $form_state->getValue('detectorstem_was_generated_by');

      $useremail = \Drupal::currentUser()->getEmail();

      // CREATE A NEW DETECTOR
      $newDetectorStemUri = Utils::uriGen('detectorstem');
      $detectorStemJson = '{"uri":"'.$newDetectorStemUri.'",'.
        '"typeUri":"'.VSTOI::DETECTOR_STEM.'",'.
        '"hascoTypeUri":"'.VSTOI::DETECTOR_STEM.'",'.
        '"hasContent":"'.$form_state->getValue('detectorstem_content').'",'.
        '"hasLanguage":"'.$form_state->getValue('detectorstem_language').'",'.
        '"hasVersion":"'.$form_state->getValue('detectorstem_version').'",'.
        '"comment":"'.$form_state->getValue('detectorstem_description').'",'.
        '"wasDerivedFrom":"'.$wasDerivedFrom.'",'.
        '"wasGeneratedBy":"'.$wasGeneratedBy.'",'.
        '"hasSIRManagerEmail":"'.$useremail.'"}';
      $api = \Drupal::service('rep.api_connector');
      $message = $api->detectorStemAdd($detectorStemJson);
      \Drupal::messenger()->addMessage(t("Added a new Detector Stem with URI: ".$newDetectorStemUri));
      $form_state->setRedirectUrl(Utils::selectBackUrl('detectorstem'));
  
    } catch(\Exception $e) {
        \Drupal::messenger()->addMessage(t("An error occurred while adding the Detector Stem: ".$e->getMessage()));
        $form_state->setRedirectUrl(Utils::selectBackUrl('detectorstem'));
    }
  }

}