<?php

namespace Drupal\sir\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\rep\Constant;
use Drupal\rep\Utils;
use Drupal\rep\Entity\Tables;
use Drupal\rep\Vocabulary\VSTOI;

class AddProcessForm extends FormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'add_process_form';
  }

  protected $sourceProcessUri;

  protected $sourceProcess;

  public function getSourceProcessUri() {
    return $this->sourceProcessUri;
  }

  public function setSourceProcessUri($uri) {
    return $this->sourceProcessUri = $uri;
  }

  public function getSourceProcess() {
    return $this->sourceProcess;
  }

  public function setSourceProcess($obj) {
    return $this->sourceProcess = $obj;
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $sourceprocessuri = NULL) {

    // MODAL
    $form['#attached']['library'][] = 'rep/rep_modal';
    $form['#attached']['library'][] = 'core/drupal.dialog';

    // ESTABLISH API SERVICE
    $api = \Drupal::service('rep.api_connector');

    // HANDLE SOURCE PROCESS,  IF ANY
    $sourceuri=$sourceprocessuri;
    if ($sourceuri === NULL || $sourceuri === 'EMPTY') {
      $this->setSourceProcess(NULL);
      $this->setSourceProcessUri('');
    } else {
      $sourceuri_decode=base64_decode($sourceuri);
      $this->setSourceProcessUri($sourceuri_decode);
      $rawresponse = $api->getUri($this->getSourceProcessUri());
      $obj = json_decode($rawresponse);
      if ($obj->isSuccessful) {
        $this->setSourceProcess($obj->body);
      } else {
        $this->setSourceProcess(NULL);
        $this->setSourceProcessUri('');
      }
    }
    $disabledDerivationOption = ($this->getSourceProcess() === NULL);

    $tables = new Tables;
    $languages = $tables->getLanguages();
    $derivations = $tables->getGenerationActivities();

    $sourceContent = '';
    if ($this->getSourceProcess() != NULL) {
      $sourceContent = $this->getSourceProcess()->hasContent;
    }

    $form['process_type'] = [
      'top' => [
        '#type' => 'markup',
        '#markup' => '<div class="pt-3 col border border-white">',
      ],
      'main' => [
        '#type' => 'textfield',
        '#title' => $this->t('Parent Type'),
        '#name' => 'process_type',
        '#default_value' => '',
        '#id' => 'process_type',
        '#parents' => ['process_type'],
        '#attributes' => [
          'class' => ['open-tree-modal'],
          'data-dialog-type' => 'modal',
          'data-dialog-options' => json_encode(['width' => 800]),
          'data-url' => Url::fromRoute('rep.tree_form', [
            'mode' => 'modal',
            'elementtype' => 'process',
          ], ['query' => ['field_id' => 'process_type']])->toString(),
          'data-field-id' => 'process_type',
          'data-elementtype' => 'process',
          'autocomplete' => 'off',
        ],
      ],
      'bottom' => [
        '#type' => 'markup',
        '#markup' => '</div>',
      ],
    ];
    $form['process_content'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Content'),
    ];
    $form['process_language'] = [
      '#type' => 'select',
      '#title' => $this->t('Language'),
      '#options' => $languages,
      '#default_value' => 'en',
    ];
    $form['process_version'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Version'),
      '#default_value' => '1',
      '#disabled' => TRUE,
    ];
    $form['process_version'] = [
      '#type' => 'hidden',
      '#value' => '1',
    ];
    $form['process_description'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Description'),
    ];
    $form['process_was_derived_from'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Was Derived From'),
      '#default_value' => $sourceContent,
      '#disabled' => TRUE,
    ];
    $form['process_was_generated_by'] = [
      '#type' => 'select',
      '#title' => $this->t('Was Generated By'),
      '#options' => $derivations,
      '#default_value' => Constant::DEFAULT_WAS_GENERATED_BY,
      '#disabled' => $disabledDerivationOption,
    ];
    $form['save_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Save'),
      '#name' => 'save',
      '#attributes' => [
        'class' => ['btn', 'btn-primary', 'save-button'],
      ],
    ];
    $form['cancel_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Cancel'),
      '#name' => 'back',
      '#attributes' => [
        'class' => ['btn', 'btn-primary', 'cancel-button'],
      ],
    ];
    $form['bottom_space'] = [
      '#type' => 'item',
      '#title' => t('<br><br>'),
    ];

    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    $submitted_values = $form_state->cleanValues()->getValues();
    $triggering_element = $form_state->getTriggeringElement();
    $button_name = $triggering_element['#name'];

    if ($button_name != 'back') {
      if(strlen($form_state->getValue('process_content')) < 1) {
        $form_state->setErrorByName('process_content', $this->t('Please enter a valid content'));
      }
      if(strlen($form_state->getValue('process_language')) < 1) {
        $form_state->setErrorByName('process_language', $this->t('Please enter a valid language'));
      }
      if(strlen($form_state->getValue('process_version')) < 1) {
        $form_state->setErrorByName('process_version', $this->t('Please enter a valid version'));
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $submitted_values = $form_state->cleanValues()->getValues();
    $triggering_element = $form_state->getTriggeringElement();
    $button_name = $triggering_element['#name'];

    if ($button_name === 'back') {
      self::backUrl();
      return;
    }

    try {

      $wasDerivedFrom = '';
      if ($this->getSourceProcessUri() === NULL) {
        $wasDerivedFrom = 'null';
      } else {
        $wasDerivedFrom = $this->getSourceProcessUri();
      }
      $wasGeneratedBy = $form_state->getValue('process_was_generated_by');

      $useremail = \Drupal::currentUser()->getEmail();

      // CREATE A NEW DETECTOR
      $newProcessUri = Utils::uriGen('process');
      $processJson = '{"uri":"'.$newProcessUri.'",'.
        '"superUri":"'.UTILS::plainUri($form_state->getValue('process_type')).'",'.
        //'"typeUri":"'.VSTOI::DETECTOR_STEM.'",'.
        '"hascoTypeUri":"'.VSTOI::PROCESS.'",'.
        '"hasStatus":"'.VSTOI::DRAFT.'",'.
        '"hasContent":"'.$form_state->getValue('process_content').'",'.
        '"hasLanguage":"'.$form_state->getValue('process_language').'",'.
        '"hasVersion":"'.$form_state->getValue('process_version').'",'.
        '"comment":"'.$form_state->getValue('process_description').'",'.
        '"wasDerivedFrom":"'.$wasDerivedFrom.'",'.
        '"wasGeneratedBy":"'.$wasGeneratedBy.'",'.
        '"hasSIRManagerEmail":"'.$useremail.'"}';
      $api = \Drupal::service('rep.api_connector');
      $message = $api->processAdd($processJson);
      \Drupal::messenger()->addMessage(t("Added a new Process with URI: ".$newProcessUri));
      self::backUrl();
      return;

    } catch(\Exception $e) {
        \Drupal::messenger()->addError(t("An error occurred while adding the Process: ".$e->getMessage()));
        self::backUrl();
        return;
      }
  }

  function backUrl() {
    $uid = \Drupal::currentUser()->id();
    $previousUrl = Utils::trackingGetPreviousUrl($uid, 'sir.add_process');
    if ($previousUrl) {
      $response = new RedirectResponse($previousUrl);
      $response->send();
      return;
    }
  }

}
